#!/usr/bin/env bash

# Author: Josenilson Ferreira da Silva
# Date: August 2024
# License: GNU General Public License v3.0

export PLATFORM
export USERNAME
export TOKEN

# Calls the message function
source ./src/default_message
set -e

# to show platform options
show_platform_options() {
    echo -e "\e[31;1mChoose a platform:\e[0m"
    echo -e "\e[34;1m1) GitHub\e[0m"
    echo -e "\e[34;1m2) GitLab\e[0m"
    echo -e "\e[34;1m3) Salsa\e[0m"
}

# to create README.md file
create_readme_file() {
    echo "Creating README.md file..."
    echo "# $repo_name" > README.md
    echo "" >> README.md
    echo "This is a repository for $repo_name." >> README.md
    echo "" >> README.md
    echo "## License" >> README.md
}

# Show platform options and get user input
show_platform_options
read -p "$(echo -e '\033[1;33mChoose the platform (1-3): \033[0m')" PLATFORM
read -p "$(echo -e '\033[1;33mWhat is the name of the repository owner? \033[0m')" USERNAME

# User prompts
read -p "$(echo -e '\033[1;33mEnter the name of the repository you want to create: \033[0m')" repo_name
read -p "$(echo -e '\033[1;33mRepository type (1: Public or 2: Private): \033[0m')" repo_type

# Set visibility based on user input
if [ "$repo_type" == "1" ]; then
    visibility="public"
elif [ "$repo_type" == "2" ]; then
    visibility="private"
else
    echo "Invalid repository type!"
    exit 1
fi

# Ask if the user wants to create a README.md
read -p "Do you want to create a README.md file? (yes/no): " create_readme

# Check the user's response
if [[ "$create_readme" == "yes" ]]; then
    create_readme_file
    echo "README.md file created successfully."
elif [[ "$create_readme" == "no" ]]; then
    echo "Skipping README.md creation."
else
    echo "Invalid input. Please enter 'yes' or 'no'."
fi

# Remote repository creation
case $PLATFORM in
    1)
        PLATFORM=GitHub
        read -p "$(echo -e '\033[1;33mEnter your GitHub access token: \033[0m')" TOKEN
        repository_search_message
        response=$(curl -s -H "Authorization: token $TOKEN" \
              -d "{\"name\":\"$repo_name\",\"private\":$([ "$visibility" == "private" ] && echo true || echo false)}" \
              https://api.github.com/user/repos)

        if echo "$response" | jq -e '.id' > /dev/null; then
            create_repository_successfully
            platform_host="github.com"
            remote_url="git@github.com:$USERNAME/$repo_name.git"
        else
            failed_create_repository
            exit 1
        fi
        ;;
    2)
        PLATFORM=GitLab
        read -p "$(echo -e '\033[1;33mEnter your GitHub access token: \033[0m')" TOKEN
        repository_search_message
        response=$(curl -s --request POST --form "name=$repo_name" \
              --form "visibility=$visibility" \
              --header "PRIVATE-TOKEN: $TOKEN" \
              "https://gitlab.com/api/v4/projects")

        if echo "$response" | jq -e '.id' > /dev/null; then
            create_repository_successfully
            platform_host="gitlab.com"
            remote_url="git@gitlab.com:$USERNAME/$repo_name.git"
        else
            failed_create_repository
            exit 1
        fi
        ;;
    3)
        PLATFORM=Salsa
        read -p "$(echo -e '\033[1;33mEnter your GitHub access token: \033[0m')" TOKEN
        repository_search_message
        response=$(curl -s --request POST --form "name=$repo_name" \
              --form "visibility=$visibility" \
              --header "PRIVATE-TOKEN: $TOKEN" \
              "https://salsa.debian.org/api/v4/projects")

        if echo "$response" | jq -e '.id' > /dev/null; then
            create_repository_successfully
            platform_host="salsa.debian.org"
            remote_url="git@salsa.debian.org:$USERNAME/$repo_name.git"
        else
            failed_create_repository
            exit 1
        fi
        ;;
    *)
        platform_invalid
        exit 1
        ;;
esac

# Export variables
export platform_host
export repo_name
export remote_url

# Call external script to create LICENSE file
./src/license_repo  --license-local --send

echo "Repository setup complete."
