#!/bin/bash


USER_DATA_FILE="$HOME/.config/gstoolbox/token"

# Lê os dados do arquivo
read -r FILE_PLATFORM FILE_USERNAME FILE_TOKEN < <(awk '{print $1, $2, $3}' "$USER_DATA_FILE")

# Testa se todos os dados estão iguais
if [[ "$PLATFORM" == "$FILE_PLATFORM" && "$USERNAME" == "$FILE_USERNAME" && "$TOKEN" == "$FILE_TOKEN" ]]; then
    echo "Todos os dados estão iguais. Saindo..."
    exit 0
fi

# Testa se PLATFORM e USERNAME são iguais, mas TOKEN é diferente
if [[ "$PLATFORM" == "$FILE_PLATFORM" && "$USERNAME" == "$FILE_USERNAME" && "$TOKEN" != "$FILE_TOKEN" ]]; then
    read -r -p "TOKEN differs, do you want to update it? (y/n): " option
    if [[ "$option" == "y" ]]; then
        # Atualiza o TOKEN
        grep -v "^$FILE_PLATFORM $FILE_USERNAME " "$USER_DATA_FILE" > "$USER_DATA_FILE.tmp"
        echo "$PLATFORM $USERNAME $TOKEN" >> "$USER_DATA_FILE.tmp"
        mv "$USER_DATA_FILE.tmp" "$USER_DATA_FILE"
        echo "TOKEN updated successfully!"
    else
        echo "TOKEN was not updated!"
    fi
fi

# Se PLATFORM ou USERNAME forem diferentes, adiciona os dados
if [[ "$PLATFORM" != "$FILE_PLATFORM" || "$USERNAME" != "$FILE_USERNAME" ]]; then
    read -r -p "Do you want to save the data for eventual use? (y/n): " option
    if [[ "$option" == "y" ]]; then
        # Incrementa os dados no arquivo, adicionando uma nova linha
        echo "$PLATFORM $USERNAME $TOKEN" >> "$USER_DATA_FILE"
        echo "Data saved successfully!"
    else
        echo "Data was not saved!"
    fi
fi
